import Foundation

// MARK: - Top-Level Script

/// A pre-choreographed light show for a known song.
/// Generated by AI from song analysis (BPM, structure, key, energy curve).
/// Loaded into Wilson and triggered on first sound detection.
struct LightScript: Codable, Sendable {
    let version: Int
    let metadata: ScriptMetadata
    let defaultState: ScriptCueState
    let cues: [ScriptCue]
    let events: [ScriptEvent]

    /// Beats per bar derived from time signature (defaults to 4).
    var beatsPerBar: Int {
        metadata.timeSignature.first ?? 4
    }

    /// Total duration in beats, if known.
    var totalBeats: Double? {
        guard let bars = metadata.durationBars else { return nil }
        return Double(bars * beatsPerBar)
    }
}

// MARK: - Metadata

struct ScriptMetadata: Codable, Sendable {
    let title: String
    let artist: String
    let bpm: Double
    /// Time signature as [numerator, denominator], e.g. [4, 4].
    var timeSignature: [Int] = [4, 4]
    /// Musical key (matches MusicalKey.rawValue).
    var key: String?
    var genre: String?
    /// Total duration in bars.
    var durationBars: Int?
}

// MARK: - Cue State (shared between defaultState and cue overrides)

/// Lighting configuration fields. All optional for sparse/carry-forward semantics.
struct ScriptCueState: Codable, Sendable {
    var palette: [LightColor]?
    var groupingStrategy: String?
    var reactivity: Double?
    var movementIntensity: Double?

    /// Merge non-nil fields from another state on top of this one.
    func merging(_ override: ScriptCueState) -> ScriptCueState {
        ScriptCueState(
            palette: override.palette ?? palette,
            groupingStrategy: override.groupingStrategy ?? groupingStrategy,
            reactivity: override.reactivity ?? reactivity,
            movementIntensity: override.movementIntensity ?? movementIntensity
        )
    }
}

// MARK: - Cue

/// A persistent lighting state at a musical position. Holds until the next cue.
struct ScriptCue: Codable, Sendable {
    /// Bar number (1-based).
    let bar: Int
    /// Beat within the bar (1.0-based, fractional for sub-beat precision).
    var beat: Double = 1.0
    /// Human-readable label for debugging/display.
    var label: String?
    /// Transition style: "snap" or "crossfade".
    var transition: String?
    /// Crossfade duration in beats.
    var transitionBeats: Double?

    // Cue state fields (flattened into the cue JSON)
    var palette: [LightColor]?
    var groupingStrategy: String?
    var reactivity: Double?
    var movementIntensity: Double?

    /// Behavior assignments keyed by group role name
    /// ("primary", "accent", "movement", "effect", "all").
    var behaviors: [String: [ScriptBehaviorAssignment]]?

    /// Absolute position in beats from song start.
    func absoluteBeat(beatsPerBar: Int) -> Double {
        Double((bar - 1) * beatsPerBar) + (beat - 1.0)
    }

    /// Extract the state fields as a ScriptCueState for merging.
    var state: ScriptCueState {
        ScriptCueState(
            palette: palette,
            groupingStrategy: groupingStrategy,
            reactivity: reactivity,
            movementIntensity: movementIntensity
        )
    }
}

// MARK: - Behavior Assignment

/// A behavior to assign to a fixture group role.
struct ScriptBehaviorAssignment: Codable, Sendable {
    /// Behavior ID matching Behavior.id (e.g. "beatPulse", "chase").
    let id: String
    /// Timing multiplier (default 1.0).
    var speed: Double?
    /// Output strength (default 1.0).
    var intensity: Double?
    /// Phase offset for staggering (default 0.0).
    var offset: Double?
    /// Blend weight (default 1.0).
    var weight: Double?
    /// Sub-variation selector (default 0).
    var variant: Int?
}

// MARK: - Event

/// A one-shot effect at a specific musical position.
struct ScriptEvent: Codable, Sendable {
    /// Bar number (1-based).
    let bar: Int
    /// Beat within the bar (1.0-based).
    var beat: Double = 1.0
    /// Event type: "blackout", "flash", "strobeBurst".
    let type: ScriptEventType
    /// Duration in beats (nil = instantaneous/single-frame).
    var durationBeats: Double?
    /// Effect intensity (0.0-1.0).
    var intensity: Double?
    /// Sub-variation selector.
    var variant: Int?

    /// Absolute position in beats from song start.
    func absoluteBeat(beatsPerBar: Int) -> Double {
        Double((bar - 1) * beatsPerBar) + (beat - 1.0)
    }
}

enum ScriptEventType: String, Codable, Sendable {
    case blackout
    case flash
    case strobeBurst
}
